# Generated by Django 2.0.4 on 2018-04-19 17:13

import addConteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addConteudo', '0002_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='aquivos',
            field=models.FileField(upload_to=addConteudo.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='manga',
            name='dtp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
