# Generated by Django 2.0.4 on 2018-04-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addConteudo', '0003_auto_20180419_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='autor',
            new_name='user',
        ),
    ]
