# Generated by Django 2.0.4 on 2018-04-25 20:57

import addConteudo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addConteudo', '0004_auto_20180419_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('aquivos', models.FileField(upload_to=addConteudo.models.user_directory_path)),
            ],
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='user',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='aquivos',
        ),
        migrations.AddField(
            model_name='arquivos',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addConteudo.Manga'),
        ),
    ]
