# Generated by Django 2.0.4 on 2018-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addConteudo', '0005_auto_20180425_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos',
            name='capitulo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
