# Generated by Django 2.0.4 on 2018-04-26 13:42

import addConteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addConteudo', '0006_arquivos_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='capa',
            field=models.FileField(default=0, upload_to=addConteudo.models.user_directory_path),
            preserve_default=False,
        ),
    ]
