# Generated by Django 2.0.4 on 2018-04-26 15:17

import addConteudo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addConteudo', '0007_manga_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('cpN', models.IntegerField()),
                ('capa', models.CharField(blank=True, max_length=250)),
                ('resumo', models.TextField(blank=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addConteudo.Manga')),
            ],
        ),
        migrations.RemoveField(
            model_name='arquivos',
            name='manga',
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='aquivos',
            field=models.FileField(upload_to=addConteudo.models.user_directory_path2),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='capitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addConteudo.Capitulos'),
        ),
    ]
