# Generated by Django 2.0.4 on 2018-05-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addConteudo', '0008_auto_20180426_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtp', models.DateTimeField(auto_now_add=True)),
                ('nota', models.IntegerField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addConteudo.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtp', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addConteudo.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='capitulos',
            name='capa',
            field=models.FileField(upload_to=''),
        ),
    ]
