# Generated by Django 2.0.4 on 2018-04-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='capa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
