# Generated by Django 2.0.4 on 2018-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
