# Generated by Django 2.0.4 on 2018-04-25 20:53

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20180418_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, upload_to=usuario.models.user_directory_path),
        ),
    ]
